#!/bin/bash

provethem="$PVS_DIR/provethems"

if [ ! -x $provethem ]; then
    provethem=`which provethem`
fi

function clean_here {
    cd $1
    if [ -f nasalib.all ]; then
	$provethem --clean nasalib.all
    else
	if ! [ -f all-theories ]; then
	    # this script assumes that every folder is a pvs library of interest
	    for i in $(ls -d */); do
		echo -e ${i%%/};
	    done >> $1/all-theories
	    $provethem --cleanbin
	    rm all-theories
	else
	    $provethem --cleanbin
	fi;
    fi;
}

if [ "$provethem" ]; then
    while read -d ':' p; do
	echo -e
	echo -e "Cleaning '$p' ..."
	clean_here "`eval echo $p`"	
    done <<< "$PVS_LIBRARY_PATH:"
else
  echo "Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH"
fi
