#!/bin/bash

if [ ! -z "$PVS_DIR" ]; then
    provethem="$PVS_DIR/provethem"
else
    provethem=`which provethem`
    if [ ! $provethem  ]; then
	printf "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH.\n"
	exit 1;
    fi
fi

readVersion() {
    if ! type "$provethem" > /dev/null 2>&1  || ! VERSION=$($provethem --version) ; then
	printf "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH.\n"
	exit 1;
    fi
}

usage() {
    readVersion
    
    echo "NAME
  dependency-all $VERSION -- Generates the dependency graphs for the PVS libraries in the current folder.

SYNOPSIS

  dependency-all <options>

DESCRIPTION
  
  Applies dependencygraph over all the libraries in the current directory that are
  listed in the all-libraries file. 

  The option -no-iterate provokes the generation of a graph for the whole collection.
  If such option is not present, one graph is generated for each library in the
  collection. When in iterative mode, the scope of application can be controlled using 
  the options --after, --before, --but, --do, --from, and --to detailed below. The order 
  implicitly referred to by all these options is the one induced by the applicable 
  all-libraries file.

  This command also accepts all the parameters accepted by dependencygraph.

OPTIONS

  --dependencies  force regeneration of .dep files

  --no-iterate    generate graph for the whole collection instead of
  		  iterating on each library

  --zoomed        zoom into the current library when in iterative mode

  --reach-from    only show the libraries reachable from the current library
                  when in iterative mode. Only the .dep files of these libraries
                  are needed. It cannot be used with --zoomed

  --after=<dir>   process all libraries after <dir>, exclusive
  --before=<dir>  process all libraries before <dir>, exclusive
  --but=<dir1>,..,<dirn>  does not process libraries <dir1>,...,<dirn>
  --do=<dir1>,..,<dirn>   process libraries <dir1>,...,<dirn>
  --from=<dir>    process all libraries from <dir>, inclusive
  --to=<dir>      process all libraries to <dir>, inclusive

  --dry-run       no action. Print call to dependencygraph

  -h|--help       prints this message
  --version       prints version information and exit

SEE ALSO
  provethem -- for iterating commands on a list of directories
"
}

ADDITIONALARGS=()
ADDITIONALDGARGS=()
COLLECTIONLABEL=()
NOITERATE=
REACHFROM=
DRYRUN=
ZOOMORCENTER=
OUTARG=

while [ $# -gt 0 ]
do
  case $1 in
    -h|-help|--help) 
	usage
	exit 0;;
    -version|--version)
	readVersion
	echo $VERSION
	exit 0;;
    -dep|-d|--dependencies)
	FORCE=--dependencies;;
    --collection-label=*)
	COLLECTIONLABEL+=("$1");;
    -no-iterate|--no-iterate)
	NOITERATE=t;;
    -dry-run|--dry-run)
	DRYRUN="--dry-run";;
    -zoomed|--zoomed)
	ZOOMED=t
	ZOOMORCENTER="--do='%DIR%' --zoom='%DIR%'";;
    -reach-from|--reach-from)
	REACHFROM=t;;
    # valid options
    --after=*|-after=*\
    	|--before=*|-before=*\
    	|--but=*|-but=*\
    	|--do=*|-do=*\
    	|--from=*|-from=*\
    	|--to=*|-to=*)
    	ADDITIONALARGS+=("$1");;
    --after|-after\
    	|--before|-before\
    	|--but|-but\
    	|--do|-do\
    	|--from|-from\
    	|--to|-to)
    	if [[ $2 == -* ]]; then
    	    if [[ $1 =~ ^-[^-].*$ ]]; then
    		echo "Warning: missing values for $1 option (expected syntax is $1 <values>)"
    	    else
    		echo "Warning: missing values for $1 option (expected syntax is $1=<values>)"
    	    fi;
    	else
    	    ADDITIONALARGS+=("$1" "$2")
    	    shift
    	fi;;
    # # invalid options
    # *)
    # 	echo "Warning: omitting unrecognized option $1";;
    *)
	ADDITIONALDGARGS+=("$1");;
  esac
  shift 
done

if [ "$ZOOMED" ] && [ "$REACHFROM" ]; then
    echo "Error: options --zoomed and --reach-from cannot be used together."
    exit 1
fi

all_libraries_file="nasalib.all"
if [ ! -f $all_libraries_file ]; then 
    all_libraries_file="all-libraries";
    if [ ! -f $all_libraries_file ]; then 
	all_libraries_file="all-theories";
	if [ -f $all_libraries_file ]; then
	    echo "Warning: all-theories is no longer supported as default input file name, please rename it to all-libraries."
	else
	    echo "Error: input file not found.";
	    exit 1;
	fi;
    fi
fi

if [ -z "$provethem" ]; then
  echo "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH"
  exit 1
fi

NASALIBPATH=`./pvs-scripts/find-pvslib NASALib --strict --quiet --format "{dir}"`

if [ ! -d "$NASALIBPATH" ]; then
    echo "Cannot find NASALib path"
    exit 1
fi

if [ -z "$NOITERATE" ]; then
    if [ "$REACHFROM" ]; then
	ZOOMORCENTER="$ZOOMORCENTER --reach-from='%DIR%'"
    elif [ -z "$ZOOMORCENTER" ]; then
	ZOOMORCENTER="--centered-at='%DIR%'"
    fi
    OUTPUTFILE='`echo %DIR%| sed "s#/#-#"`'
    if [ "$ZOOMED" ]; then
	OUTPUTFILE="$OUTPUTFILE-zoomed"
    fi
    if [ "$REACHFROM" ]; then
	OUTPUTFILE="$OUTPUTFILE-reach"
    fi
    OUTARG="--out=$OUTPUTFILE"
fi

dgcommand=("$NASALIBPATH/pvs-scripts/dependencygraph" $FORCE "${COLLECTIONLABEL[@]}" --svg --rankdir=TB --splines=polyline "${ADDITIONALDGARGS[@]}")

if [ "$NOITERATE" ]; then
    command=("${dgcommand[@]}" "$all_libraries_file")
else
    # The shell command is run by provethem for each library, after it
    # replaces %DIR%. ZOOMORCENTER and OUTARG are not quoted because they
    # contain %DIR% and backquotes that the shell must expand.
    shcommand="$(printf '%q ' "${dgcommand[@]}")$ZOOMORCENTER $OUTARG $(printf '%q' "$all_libraries_file") && mv $OUTPUTFILE.svg %DIR%/"
    command=("$provethem" "${ADDITIONALARGS[@]}" --execute "$shcommand" --action-name=Plotting "$all_libraries_file")
fi

if [ "$DRYRUN" ]; then
    echo "About to run:"
    printf '%q ' "${command[@]}"
    echo
else
    "${command[@]}"
fi
