#! /bin/bash

# Retrieve the latest Hypatheon database file.
# Requires the curl utility.  The -k option suppresses SSL certificate
# verification, which sometimes fails.

# Run this script from the nasalib directory.

FNAME=$(curl -k https://shemesh.larc.nasa.gov/people/old/bld/ftp/latest-nasalib-hyp-db)

curl -k https://shemesh.larc.nasa.gov/people/old/bld/ftp/$FNAME -o $FNAME

