#!/usr/bin/env perl
use Getopt::Long;

$usageln = "Usage: find-all [--help | <option> ] <regexpr>";

sub usage() {
    print <<EOF;
find -- finds regular strings on NASA Libraries

$usageln
<option> may be
  --after=<dir>
    find <regexpr> in all libraries after <dir>, exclusive.
  --before=<dir>          
    find <regexpr> in all libraries before <dir>, exclusive.
  --but=<dir1>,..,<dirn>  
    exclude libraries <dir1>,...,<dirn>
  --do=<dir1>,..,<dirn>   
    find <regexpr> in libraries <dir1>,...,<dirn>
  --from=<dir>            
    find <regexpr> in libraries from <dir>, inclusive.
  --to=<dir>              
    find <regexpr> in libraries upto <dir>, inclusive.
  --pvs
    find in .pvs files (default)
  --prf
    find in .prf files only unless --pvs is specified
  --help
    print this message.
EOF
    exit;
}

GetOptions('after=s'=>\$after,
           'before=s'=>\$before,
	   'but=s'=>\$but,
	   'do=s'=>\$do,
           'from=s'=>\$from,
           'to=s'=>\$to,
	   'help'=>\$help,
	   'prf'=>\$prf,
	   'pvs'=>\$pvs,
           'test'=>\$test
    ) or exit 1;

usage if $help;
$what = shift;
die "$usageln\n" if !$what || shift; 

$options .= "--after=$after " if $after;
$options .= "--before=$before " if $before;
$options .= "--but=$but " if $but;
$options .= "--do=$do " if $do;
$options .= "--from=$from " if $from;
$options .= "--to=$to " if $to;
$options .= "--test " if $test;

$files = "*.pvs";
$files = "*.prf" if $prf;
$files .= " *.pvs" if $prf && $pvs;

$provethem = "../provethem";

if (! -x $provethem) {
  $provethem = `which provethem`;
}

die "Directory where PVS is installed must be in the environment variable PATH for this command to work\n" if !$provethem;

$command = `../provethem $options--execute \"grep -e $what $files\" nasalib.all`;
print "$command\n";
