#!/usr/bin/env perl
use Getopt::Long;

$VERSION="ProofLite-7.1.0 (05/06/20)";
$FINDALLVERSION="find-all - $VERSION";

$usageln = "find-all [--help | <option>* ] <regexpr>";

sub usage() {
  print <<EOF;
NAME
  $FINDALLVERSION -- searches strings matching a given regular expressions in PVS libraries.

SYNOPSIS

  $usageln

DESCRIPTION

  By default, it finds in all the libraries which are reachable from the current 
  directory. 

  A library is considered reachable in a given directory <dir> if it is one of its 
  direct subfolders and there is a text file named all-theories in <dir> and
  the library is mentioned there. The scope of application of find-all can be 
  restricted using the options --after, --before, --but, --do, --from, and --to 
  detailed below. The order implicitly referred to by all these options is the one 
  induced by the applicable all-theories file.

OPTIONS

  --pvs             find in .pvs files (default)
  --prf             find in .prf files 
  --strategies      find in pvs-strategies files
  --attachment      find in pvs-attachment files

  --after=<dir>     find <regexpr> in all libraries after <dir>, exclusive
  --before=<dir>    find <regexpr> in all libraries before <dir>, exclusive
  --but=<dir1>,..,<dirn>  exclude libraries <dir1>,...,<dirn>
  --do=<dir1>,..,<dirn>  find <regexpr> in libraries <dir1>,...,<dirn>
  --from=<dir>      find <regexpr> in libraries from <dir>, inclusive
  --to=<dir>        find <regexpr> in libraries upto <dir>, inclusive

  --help            print this message
EOF
    exit;
}

GetOptions('after=s'=>\$after,
           'before=s'=>\$before,
	   'but=s'=>\$but,
	   'do=s'=>\$do,
           'from=s'=>\$from,
           'to=s'=>\$to,
	   'help'=>\$help,
	   'prf'=>\$prf,
	   'pvs'=>\$pvs,
	   'strategies'=>\$strategies,
	   'attachments'=>\$attachments,
           'test'=>\$test
    ) or exit 1;

usage if $help;
$what = shift;
die "$usageln\n" if !$what || shift; 

$options = "";
$options .= "--after=$after " if $after;
$options .= "--before=$before " if $before;
$options .= "--but=$but " if $but;
$options .= "--do=$do " if $do;
$options .= "--from=$from " if $from;
$options .= "--to=$to " if $to;
$options .= "--test " if $test;

$files = "";
$files .= " *.prf" if $prf;
$files .= " pvs-strategies" if $strategies;
$files .= " pvs-attachments" if $attachments;
$files .= " *.pvs" if !$files || $pvs;

$provethem = "$ENV{'PVS_DIR'}/provethem";

if (! -x $provethem) {
  $provethem = `which provethem`;
}

die "Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH\n" if !$provethem;

$file='';
$file='all-theories'  if ( -f "all-theories" );
$file='nasalib.all' if ( -f "nasalib.all" );

die "Error: neither all-theories nor nasalib.all file found.\n" if (! $file);

$command = `$provethem $options--execute \"ls $files 1> /dev/null 2>&1 && grep --exclude orphaned-proofs.prf -e '$what' $files\" $file`;
print "$command\n";
