#!/bin/bash

if [ ! -d "$PVS_DIR" ]; then
    PVS_DIR=..
fi
rsync pvs-patches/proveit.in $PVS_DIR/proveit
rsync pvs-patches/provethem.in $PVS_DIR/provethem
rsync pvs-patches/pvsio.in $PVS_DIR/pvsio
cd $PVS_DIR;bin/relocate
