#!/usr/bin/env perl
use Getopt::Long;

$ver=`grep '\*nasalib-version\*' RELEASE/nasalib.lisp`;

GetOptions('release'=>\$release,
           'longrelease'=>\$longrelease) or exit 1;

if ($release) {
  print $1 if $ver =~/\*nasalib-version\* "([^\s]+).*"/;
} elsif ($longrelease) {
  print $1 if $ver =~/\*nasalib-version\* "(.+)"/;
} else {
  print "NASALib $1" if $ver =~/\*nasalib-version\* "(.+)"/;
}
