#!/usr/bin/env perl
use Getopt::Long;

$ver=`head -n 1 RELEASE/CHANGES.txt`;

GetOptions('release'=>\$release,
           'longrelease'=>\$longrelease) or exit 1;

if ($release) {
  print $1 if $ver =~/Library ([^\s]+)/;
} elsif ($longrelease) {
  print $1 if $ver =~/Library (.+)/;
} else {
  print "$ver";
}
