#!/usr/bin/env perl
use Getopt::Long;

$ver=`grep '\*nasalib-version\*' RELEASE/nasalib.lisp`;

GetOptions('release'=>\$release,
           'longrelease'=>\$longrelease,
	   'help'=>\$help) or die "nasalib-version [--help | --release | --longrelease]\n";

if ($help) {
  print "nasalib-version [--help | --release | --longrelease]\n";
} elsif ($release) {
  print $1 if $ver =~/\*nasalib-version\* "([^\s]+).*"/;
} elsif ($longrelease) {
  print $1 if $ver =~/\*nasalib-version\* "(.+)"/;
} else {
  print "NASALib $1\n" if $ver =~/\*nasalib-version\* "(.+)"/;
}
