#!/bin/sh

if [ ! -z "$PVS_DIR" ]; then
    provethem="$PVS_DIR/provethem"
else
    provethem=`which provethem`
    if [ ! $provethem  ]; then
	printf "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH.\n"
	exit 1;
    fi
fi

readVersion() {
    if ! type "$provethem" > /dev/null 2>&1  || ! VERSION=$($provethem --version) ; then
	printf "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH.\n"
	exit 1;
    fi
}

usage() {
    echo "NAME
  prove-all $VERSION -- runs proveit on all the libraries in the NASALib

SYNOPSIS

  prove-all <options>

DESCRIPTION
  This script wraps provethem to provide a specific kind of run. By default, it removes 
  .pvscontext and the binary files from the pvsbin folder in each library directory, replaces 
  the pvs library path by the current directory, and runs proveit as indicated by the 
  nasalib.all file. As a side effect, it generates the dependency and tptp files as needed
  by each library.

  To supersede this particular configuration, the same options accepted by provethem can
  be used on this script.

OPTIONS
  prove-all accepts all the provethem options. The only own options are

   -h|--help           print this message
   --version           print version information and exit

SEE ALSO
  provethem -- for iterating proveit on a list of directories
"
}

ADDITIONALARGS=
CLEANOPT="--clean-only"

while [ $# -gt 0 ]
do
  case $1 in
    -h|-help|--help)    
	usage
	exit 0;;
    -version|--version)     
	readVersion
	echo $VERSION
	exit 0;;
    --clean|--cleanall)
	CLEANOPT=$1;;
    *)
	ADDITIONALARGS="$ADDITIONALARGS $1";;
  esac
  shift 
done 

all_theories_file="nasalib.all"
if [ ! -f $all_theories_file ]; then 
    all_theories_file="all-theories";
    if [ ! -f $all_theories_file ]; then 
	echo "Error: $all_theories_file not found.";
	exit 1;
    fi
fi

if [ "$provethem" ]; then
    # export PROVEALLVERSION="prove-all $VERSION"
    $provethem $CLEANOPT $ADDITIONALARGS $all_theories_file
    $provethem --clearpath --addpath --force $ADDITIONALARGS $all_theories_file
else
    echo "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH"
fi
