#!/bin/sh

VERSION="ProofLite-7.0.0 (04/21/20)"

export PROVEALLVERSION="prove-all - $VERSION"

usage() {
    echo "NAME
  $PROVEALLVERSION -- runs proveit on all the libraries in the NASALib

SYNOPSIS

  prove-all <options>

DESCRIPTION
  This script wraps provethem to provide a specific kind of run. By default, it removes 
  .pvscontext and the binary files from the pvsbin folder in each library directory, replaces 
  the pvs library path by the current directory, and runs proveit as indicated by the 
  nasalib.all file. As a side effect, it generates the dependency and tptp files as needed
  by each library.

  To supersede this particular configuration, the same options accepted by provethem can
  be used on this script.

OPTIONS
  prove-all accepts all the provethem options. The only own options are

   -h|--help           print this message
   --version           print version information and exit

SEE ALSO
  provethem -- for iterating proveit on a list of directories
"
}

ADDITIONALARGS=
CLEANOPT="--clean-only"

while [ $# -gt 0 ]
do
  case $1 in
    -h|-help|--help)    
	usage
	exit 0;;
    -version|--version)     
	echo $PROVEALLVERSION
	exit 0;;
    --clean|--cleanall)
	CLEANOPT=$1;;
    *)
	ADDITIONALARGS="$ADDITIONALARGS $1";;
  esac
  shift 
done 

[ ! -f nasalib.all ] && { echo "Error: nasalib.all not found."; exit 1;}

provethem="../provethem"

if [ ! -x $provethem ]; then
    provethem=`which provethem`
fi

if [ "$provethem" ]; then
  $provethem $CLEANOPT $ADDITIONALARGS nasalib.all
  $provethem --clearpath --addpath --force $ADDITIONALARGS nasalib.all
else
  echo "Error: directory where PVS is installed must be in the environment variable PATH for this command to work"
fi
