#!/usr/bin/env perl
use Getopt::Long;

$usageln = "Usage: restore-all [--help | <option> ]";

sub usage() {
    print <<EOF;
restore -- restores regular strings on NASA Libraries

$usageln
<option> may be
  --after=<dir>
    restore <regexpr> in all libraries after <dir>, exclusive.
  --before=<dir>          
    restore <regexpr> in all libraries before <dir>, exclusive.
  --but=<dir1>,..,<dirn>  
    exclude libraries <dir1>,...,<dirn>
  --do=<dir1>,..,<dirn>   
    restore <regexpr> in libraries <dir1>,...,<dirn>
  --from=<dir>            
    restore <regexpr> in libraries from <dir>, inclusive.
  --to=<dir>              
    restore <regexpr> in libraries upto <dir>, inclusive.
  --pvs
    restore in .pvs files (default)
  --prf
    restore in .prf files only unless --pvs is specified
  --help
    print this message.
EOF
    exit;
}

GetOptions('after=s'=>\$after,
           'before=s'=>\$before,
	   'but=s'=>\$but,
	   'do=s'=>\$do,
           'from=s'=>\$from,
           'to=s'=>\$to,
	   'help'=>\$help,
	   'prf'=>\$prf,
	   'pvs'=>\$pvs,
           'test'=>\$test
    ) or exit 1;

usage if $help;
die "$usageln\n" if shift; 

$options .= "--after=$after " if $after;
$options .= "--before=$before " if $before;
$options .= "--but=$but " if $but;
$options .= "--do=$do " if $do;
$options .= "--from=$from " if $from;
$options .= "--to=$to " if $to;
$options .= "--test " if $test;

$files = "*.pvs";
$files = "*.prf" if $prf;
$files .= " *.pvs" if $prf && $pvs;

$provethem = "$ENV{'PVS_DIR'}/provethem";

if (! -x $provethem) {
  $provethem = `which provethem`;
}

die "Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH\n" if !$provethem;

$file='';
if ( -f 'nasalib.all' ) {
  $file='nasalib.all'
}
  
$command = `$provethem $options--execute \"test -f pvsbin/top.dep || git checkout -- pvsbin/top.dep\" $file`;

print "$command\n";
