#!/usr/bin/env perl
use strict;
use warnings;
use Getopt::Long;
use File::Basename;
use Cwd qw(abs_path);

my $findpvslib = basename($0);
my $pvslib = '.pvslib';
my $default_format = "{id} - {dir}";

my $help_str = "NAME
  $findpvslib -- find PVS library records

SYNOPSIS
  $findpvslib [ --help | <options> ] [<libname>]*

  Find library records in PVS_LIBRARY_PATH whose ids match <libname>. By default, match is case
  insensitive and partial unless the flag --strict is provided.

OPTIONS
  Options are processed in the order they appear. Options marked [+] can be
  used multiple times and are cumulative. One letter options can be combined.

[*]--add-path <path>
     Add <path> to PVS_LIBRARY_PATH, where <path> is a colon separated list of directories
   --clear-path
     Clear PVS_LIBRARY_PATH
   --format <formatstr>
     If keys are not provided, print library records using the format string <formatstr>.
     This string may contain metavariables of the form \"{key}\", which are replaced by the actual
     key value. The metavariable {default} represents \"$default_format\".
     If --format and --key are both provided, --key options are ignored
[*]--key <keyname>
     Select key <keyname> of every library record
   --quiet
     Be silent
   --strict
     Find library records whose ids exactly match <libname>

EXAMPLES
  * $findpvslib
    Print all library records and their keys

  * $findpvslib --format \"{id} {version} ({date})\"
    Print all library records in the provided format

  * $findpvslib NASALib --strict --format \"{default}\"
    Print all keys of the record of NASALib using the default format

  * $findpvslib nasa --key dir --key date
    Print speficied keys of library records matching \"nasa\" (case insensitive)

TECHNICAL COMMENT:
  This command searches a file called $pvslib in the root of each directory in PVS_LIBRARY_PATH. This file
  is assumed to be a set of lines of the form <key>:<val>. This file is considered to
  be a record storing meta-information of a library. Keys are semantic agnostic, except for the following ones:
  * \"id\": Library id, assumed to be globally unique. If not provided, it is assummed to be the basename of the path.
  * \"dir\": This is an implict key in every record and points to the absolute directory of the library.
  * \"sublibdirs\": Comma separated list of directories, relative to the library, containing sublibraries. These directories
    will automatically be added to PVS_LIBRARY_PATH by PVS.
  * \"lisploads\": Comma separated list of files, relative to the library, containing lisp code. These files will
    be automatically loaded by PVS.
  * \"preludedirs\": Comma separated list of prelude extension directories, which are relative to the library.
";

my @keys;
my $strict;
my $quiet;
my $format;
my $clearpath;
my @addpath = split(":",$ENV{PVS_LIBRARY_PATH});
my $help;

GetOptions('key=s' => \@keys,
	   'strict' => \$strict,
	   'quiet' => \$quiet,
	   'format=s' => \$format,
	   'clear-path' => sub { @addpath = (); },
	   'add-path=s' => sub {
	     my ($opt_name, $opt_value) = @_;
	     my @dir = split(":",$opt_value);
	     @dir = map { abs_path($_) } @dir;
	     push(@addpath,join ":",@dir);
	   },
	   'help' => \$help) or
    die "\n";

my @libnames = @ARGV;

die "Flag --strict requires a <libname>\n" if $strict && !@libnames;

if ($help) {
  print "$help_str";
  exit(1);
}
my %pvslibs;     # Hash of all library hashes
my %dups;        # Hash of ids that are duplicated. The key is the id and the val is a list of paths to the .pvslib files
my %nosubdirs;   # Hash of ids without valid subdirs. The key is the id and the val is a list of directories
my %nolisploads; # Hash of ids without valid lisp load files. The key is the id and the val is a list of files
my @noids;       # List of .pvslib without ids
my @foundlibs;   # List of found libraries that need to be processed

my $pvslibrarypath = join ":", @addpath;

my @dirs = split(':',$pvslibrarypath);
foreach my $dir (@dirs) {
  my %data;
  my $base = basename($dir);
  my @fields = ( $base );
  $data{"id"} = \@fields;
  if (-e "$dir/$pvslib") {
    open(FH, '<', "$dir/$pvslib");
    while(<FH>) {
      $_ =~ s/#.*$//;
      next if /^\s*$/;  # Skip empty lines
      my @fields = split(':',$_);
      next if scalar(@fields) <= 1;
      my $key = shift @fields;
      if (scalar(@fields) == 1) {
	@fields = split(",",$fields[0]);
      }
      s{^\s+|\s+$}{}g foreach @fields; # Trim spaces of all fields
      $data{$key} = \@fields;
    }
    close(FH);
  }
  my @thisdir;
  push @thisdir, $dir;
  $data{'dir'} = \@thisdir;
  my $libid = $data{'id'}[0];
  if ($libid) {
    if ($pvslibs{$libid}) { # id is already in the list
      # id is duplicated
      if ($dups{$libid}) { # id is already known to be duplicated
	push @{$dups{$libid}}, "$dir/$pvslib";
      } else { # id is a new duplicate
	my @thisdup;
	push @thisdup, "$pvslibs{$libid}{'dir'}[0]", "$dir/$pvslib";
	$dups{$libid} = \@thisdup;
      }
    } else {
      # Only non-duplicated id's are processed
      $pvslibs{$libid} = \%data;

      # Add sublibs to $pvslibrarypath
      my @subdirs = @{$data{'sublibdirs'}} if $data{'sublibdirs'};
      if (@subdirs) {
	for my $subdir (@subdirs) {
	  if ( -d "$dir/$subdir" ) {
	    push @dirs,"$dir/$subdir";
	  } elsif ($nosubdirs{$libid}) {
	    push @{$nosubdirs{$libid}},"$dir/$subdir";
	  } else {
	    my @thissubdir;
	    push @thissubdir,"$dir/$subdir";
	    $nosubdirs{$libid} = \@thissubdir;
	  }
	}
      }

      # Check lispload files exist
      my @lisploads = @{$data{'lisploads'}} if $data{'lisploads'};
      for my $lispload (@lisploads) {
	next if -e "$dir/$lispload";
	if ($nolisploads{$libid}) {
	  push @{$nolisploads{$libid}},"$dir/$lispload";
	} else {
	  my @thislisp;
	  push @thislisp, "$dir/$lispload";
	  $nolisploads{$libid} = \@thislisp;
	}
      }

      if ( !@libnames || ($strict && grep { $libid eq $_ } @libnames) ||
	   (!$strict && grep { $libid =~ m/$_/i } @libnames) ) {
	## This record has to be processed
	push @foundlibs, $libid;
	last if $strict;
      }
    }
  } else { # No id
    push @noids, "$dir/$pvslib";
  }
}

# Print check message
my $checkmsg;
my $msg = "";
if (!$quiet) {
  $msg = join ",", @noids;
  $checkmsg .= "Warning: $pvslib without library id ($msg)\n" if $msg;
  for my $id (keys %dups) {
    my $msgstr = join ":", @{$dups{$id}};
    $checkmsg .= "Warning: Duplicated library id $id ($msgstr)\n";
  }
  for my $id (keys %nosubdirs) {
    my $msgstr = join ":", @{$nosubdirs{$id}};
    $checkmsg .= "Warning: Library sub directories of library $id not found ($msgstr)\n";
  }
  for my $id (keys %nolisploads) {
    my $msgstr = join ":", @{$nolisploads{$id}};
    $checkmsg .= "Warning: Lisp load files of library $id not found ($msgstr)\n";
  }
}

if (!@foundlibs) {
  my $strictstr = "";
  $strictstr = " strictly" if $strict;
  my $libnamestr = join ",", @libnames;
  $libnamestr = "any id" unless $libnamestr;
  $checkmsg .= "No library id$strictstr matching $libnamestr found in files $pvslib in PVS_LIBRARY_PATH\n";
}

## Processing the found libraries

sub compare {
  if ($a eq "id") {
    return -1;
  } elsif ($b eq "id") {
    return 1;
  } else {
    return $a cmp $b;
  }
}

print "PVS_LIBRARY_PATH=$pvslibrarypath\n" if !$quiet;

for my $libid (@foundlibs) {
  my %data = %{$pvslibs{$libid}};
  my @datakeys = keys %data;

  if ($format) {
    my $str = $format;
    $str =~ s/{default}/$default_format/g;
    for my $key ( @datakeys ) {
      $str =~ s/{$key}/@{$data{$key}}/g;
    }
    $str =~ s/{[A-Za-z][A-Za-z0-9_]*}//g;
    print "$str\n";
  } else {
    if (@keys) {
      @datakeys = split(",",join ",", @keys);
      unshift(@datakeys,'id') unless grep { 'id' eq $_ } @datakeys;
    } else {
      @datakeys = sort compare @datakeys;
    }
    my $n = $#datakeys;
    for my $key ( @datakeys ) {
      my $valstr = "";
      $valstr = join ", ", @{$data{$key}} if $data{$key};
      print "$key:$valstr";
      print " | " if $n;
      $n--;
    }
    print("\n");
  }
}

die "$checkmsg" if $checkmsg;
