#!/bin/bash

# Assumes NASALib location is set in PVS_LIBRARY_PATH

[ ! -d "$PVS_LIBRARY_PATH" ] && echo "Can't recognize $PVS_LIBRARY_PATH as a directory, please indicate NASALib dir in PVS_LIBRARY_PATH" && exit 1

echo "Processing NASALib located at $PVS_LIBRARY_PATH"

EXCLUDING='-e "2021" -e "cpnf_stats" -e "mash_them_all.out*" -e "*csv" -e "*out" -e "*bak" -e "features-2_stats*"'

# stage-pvs --command  "cd \$PVS_LIBRARY_PATH; ./prove-all --do Bernstein,Sturm,analysis,decimals,matrices,orders" $@

if [ -z $1 ]; then
    stage-pvs --command  "cd \$PVS_LIBRARY_PATH; time ./prove-all --pid" -d nasalib $EXCLUDING
else
    DIRNAME="nasalib_${1//,/_}"
    stage-pvs --command  "cd \$PVS_LIBRARY_PATH; time ./prove-all --pid --do $1" -d $DIRNAME $EXCLUDING
fi
    
