(defun latex-print-finish (&optional (top-filename "pvs-files") target-dir (supersede? t))
  (let ((top-pathname (make-pathname :directory target-dir
				     :name top-filename :type "tex")))
    (if (and (not supersede?) (probe-file top-pathname))
	(let ((lines (with-open-file (stream top-pathname)
		       (loop for line = (read-line stream nil)
			     while line
			     collect line))))
	  (with-open-file (stream top-pathname :direction :output :if-exists :supersede)
	    (loop for line in (butlast lines)
		  do (write-line line stream))
	    (format stream "~:{\\markright{~a}\\label{~a}~:*\\input{~a}\\newpage
~}
\\end{document}" (mapcar #'(lambda (name)
					  (let ((fname (pathname-name name)))
					    (list (latex-protect fname) fname)))
				      (reverse *latex-files*)))))
	(with-open-file (mods top-pathname
			      :direction :output
			      :if-exists :supersede
			      :if-does-not-exist :create)

	  (format mods "~
% Automatically generated by PVS ~a
\\documentclass[12pt]{article}
\\usepackage{alltt}
\\usepackage{fullpage}
\\usepackage{supertabular}
\\usepackage{~apvs}
\\usepackage{iftex}
\\usepackage{amssymb}
\\ifluatex
\\usepackage{fontspec}
\\usepackage[math-style=ISO]{unicode-math}
\\setmainfont[Numbers=OldStyle, Ligatures=TeX]{TeX Gyre Termes}
\\setmathfont[Numbers=Lining]{TeX Gyre Termes Math}
\\setmathfont[range=\\bigstar]{XITS Math}
\\setmathfont[range=\\rightsquigarrow]{XITS Math}
\\setmathfont[range=\\int]{TeX Gyre Termes Math} % just to get parameters from this font
\\else
\\usepackage[T1]{fontenc}
\\usepackage[utf8]{inputenc}
\\fi
\\renewcommand{\\leadsto}{\\rightsquigarrow}
\\begin{document}
~{\\input{~a}~%~}
~:{\\markright{~a}\\label{~a}~:*\\input{~a}\\newpage
~}
\\end{document}
"
		  *pvs-version*
		  (environment-variable "PVSPATH")
		  *latex-substitutions*
		  (mapcar #'(lambda (name)
			      (let ((fname (pathname-name name)))
				(list (latex-protect fname) fname)))
			  (reverse *latex-files*)))))
    top-pathname))
