;; groundeval/cl2pvs.lisp
(defmethod cl2pvs* (sexpr (type type-name) context)
  (declare (ignore context))
  (if (tc-eq (find-supertype type) *number*)
      (cond ((rationalp sexpr) (mk-number-expr sexpr))
	    ;; ((floatp sexpr)(mk-number-expr sexpr))
	    ((floatp sexpr)(mk-number-expr (rationalize sexpr)))
	    (t (error 'cl2pvs-error :sexpr sexpr :type type)))
    (if (tc-eq (find-supertype type) *boolean*)
	(if sexpr (if (eq sexpr *cant-translate*)
		      (error 'cl2pvs-error :sexpr sexpr :type type)
		    *true*)
	  *false*)
      (error 'cl2pvs-error :sexpr sexpr :type type))))
